import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    errorContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: Spacing.lg,
    },
    backButton: {
      marginTop: Spacing.md,
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.lg,
      borderRadius: BorderRadius.md,
      backgroundColor: theme.backgroundTertiary,
    },
    // 顶部工具栏 - 紧凑
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.borderLight,
      backgroundColor: theme.backgroundRoot,
    },
    topBarButton: {
      padding: Spacing.xs,
    },
    topBarRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    searchButton: {
      padding: Spacing.xs,
      borderRadius: 6,
      backgroundColor: theme.backgroundTertiary,
    },
    novelInfo: {
      flex: 1,
      marginHorizontal: Spacing.sm,
    },
    chapterSelector: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 1,
      gap: 2,
    },
    // 章节下拉
    chapterDropdown: {
      position: 'absolute',
      top: 44,
      left: Spacing.md,
      right: Spacing.md,
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.md,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 5,
      zIndex: 100,
      maxHeight: 240,
    },
    chapterDropdownHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: Spacing.md,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.borderLight,
    },
    chapterDropdownList: {
      maxHeight: 180,
    },
    chapterDropdownItem: {
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.borderLight,
    },
    chapterDropdownItemActive: {
      backgroundColor: theme.backgroundTertiary,
    },
    // 书写区域 - 最大化
    writingArea: {
      flex: 1,
      backgroundColor: theme.backgroundDefault,
    },
    writingContent: {
      padding: Spacing.md,
      paddingBottom: Spacing.lg,
      flexGrow: 1,
    },
    writingContentKeyboard: {
      paddingBottom: Spacing.md,
    },
    contentInput: {
      fontSize: 16,
      lineHeight: 26,
      color: theme.textPrimary,
      textAlign: 'justify',
      minHeight: 500,
    },
    // 底部工具栏 - 紧凑
    inputToolbar: {
      borderTopWidth: 0.5,
      borderTopColor: theme.borderLight,
      backgroundColor: theme.backgroundRoot,
    },
    // 格式工具栏
    formatToolbar: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.xs,
      gap: 2,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.borderLight,
      backgroundColor: theme.backgroundTertiary,
    },
    formatBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      width: 32,
      height: 28,
      borderRadius: 4,
      backgroundColor: theme.backgroundDefault,
    },
    formatBtnActive: {
      backgroundColor: 'rgba(200, 16, 46, 0.1)',
      borderWidth: 1,
      borderColor: '#C8102E',
    },
    formatDivider: {
      width: 1,
      height: 20,
      backgroundColor: theme.borderLight,
      marginHorizontal: 4,
    },
    highlightIcon: {
      width: 18,
      height: 18,
      borderRadius: 9,
      borderWidth: 2,
      borderColor: theme.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    characterBar: {
      flexDirection: 'row',
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.xs,
      gap: Spacing.sm,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.borderLight,
    },
    characterChip: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.backgroundTertiary,
      paddingVertical: 2,
      paddingHorizontal: Spacing.sm,
      borderRadius: BorderRadius.full,
      gap: 4,
    },
    addCharacterChip: {
      borderWidth: 1,
      borderColor: '#C8102E',
      backgroundColor: 'transparent',
      justifyContent: 'center',
    },
    controlBar: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      gap: Spacing.sm,
    },
    modeButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 6,
      paddingHorizontal: Spacing.sm,
      borderRadius: BorderRadius.sm,
      backgroundColor: theme.backgroundTertiary,
    },
    // 标点符号快捷输入
    punctuationBar: {
      flex: 1,
      marginHorizontal: Spacing.xs,
    },
    punctuationContent: {
      flexDirection: 'row',
      gap: 2,
    },
    punctuationBtn: {
      width: 28,
      height: 28,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.sm,
    },
    // 保存按钮 - 与格式工具栏同行
    saveButtonInline: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 6,
      paddingHorizontal: Spacing.sm,
      borderRadius: BorderRadius.sm,
      backgroundColor: '#059669', // 绿色
    },
    saveButtonDisabled: {
      opacity: 0.6,
    },
    aiButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 6,
      paddingHorizontal: Spacing.md,
      borderRadius: BorderRadius.sm,
      backgroundColor: '#C8102E',
    },
    aiButtonDisabled: {
      opacity: 0.6,
    },
    voiceButton: {
      position: 'absolute',
      bottom: 100,
      left: 0,
      right: 0,
      alignItems: 'center',
    },
    voiceButtonInner: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: '#C8102E',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#C8102E',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
    },
    // 章节输入对话框
    chapterInputOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1000,
    },
    chapterInputDialog: {
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.md,
      padding: Spacing.lg,
      width: '80%',
      maxWidth: 280,
    },
    chapterInputTitle: {
      marginBottom: Spacing.md,
      textAlign: 'center',
    },
    chapterInputField: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: BorderRadius.sm,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.sm,
      fontSize: 14,
      color: theme.textPrimary,
      marginBottom: Spacing.md,
    },
    chapterInputActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: Spacing.sm,
    },
    chapterInputCancel: {
      paddingVertical: Spacing.xs,
      paddingHorizontal: Spacing.md,
      borderRadius: BorderRadius.sm,
      backgroundColor: theme.backgroundTertiary,
    },
    chapterInputConfirm: {
      paddingVertical: Spacing.xs,
      paddingHorizontal: Spacing.md,
      borderRadius: BorderRadius.sm,
      backgroundColor: '#C8102E',
    },
    // AI续写弹窗
    continueModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-end',
    },
    continueModalContent: {
      backgroundColor: theme.backgroundRoot,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingHorizontal: Spacing.md,
      paddingBottom: Spacing.xl,
      paddingTop: Spacing.md,
    },
    continueModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.sm,
    },
    continueInput: {
      backgroundColor: theme.backgroundTertiary,
      borderRadius: 8,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      fontSize: 14,
      color: theme.textPrimary,
      minHeight: 80,
      textAlignVertical: 'top',
    },
    continueQuickOptions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.xs,
      marginTop: Spacing.sm,
      marginBottom: Spacing.md,
    },
    quickOption: {
      paddingVertical: Spacing.xs,
      paddingHorizontal: Spacing.sm,
      borderRadius: 16,
      backgroundColor: theme.backgroundTertiary,
      borderWidth: 1,
      borderColor: '#C8102E',
    },
    continueGenerateButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#C8102E',
      paddingVertical: Spacing.md,
      borderRadius: 8,
    },
    // 角色详情弹窗
    characterModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    characterModalContent: {
      backgroundColor: theme.backgroundDefault,
      borderRadius: 16,
      width: '85%',
      maxWidth: 320,
      maxHeight: '80%',
      overflow: 'hidden',
    },
    characterModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: Spacing.md,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.borderLight,
    },
    characterModalTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    characterAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
    },
    characterModalBody: {
      padding: Spacing.md,
      maxHeight: 400,
    },
    characterInfoRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: Spacing.xs,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.borderLight,
    },
    characterInfoLabel: {
      width: 60,
    },
    characterInfoSection: {
      paddingVertical: Spacing.sm,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.borderLight,
    },
    characterInfoValue: {
      marginTop: 4,
      lineHeight: 20,
    },
    traitsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: 6,
    },
    traitTag: {
      paddingVertical: 3,
      paddingHorizontal: 10,
      borderRadius: 12,
      backgroundColor: 'rgba(200, 16, 46, 0.1)',
    },
    characterModalClose: {
      padding: Spacing.md,
      alignItems: 'center',
      borderTopWidth: 0.5,
      borderTopColor: theme.borderLight,
    },
    // 格式设置弹窗
    formatModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    formatModalContent: {
      backgroundColor: theme.backgroundDefault,
      borderRadius: 16,
      width: '80%',
      maxWidth: 300,
      overflow: 'hidden',
    },
    formatModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: Spacing.md,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.borderLight,
    },
    formatOptions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      padding: Spacing.sm,
      gap: Spacing.xs,
    },
    formatOption: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
      borderRadius: 8,
      backgroundColor: theme.backgroundTertiary,
      gap: 6,
    },
    formatOptionActive: {
      backgroundColor: 'rgba(200, 16, 46, 0.1)',
      borderWidth: 1,
      borderColor: '#C8102E',
    },
    colorPreview: {
      width: 16,
      height: 16,
      borderRadius: 8,
    },
    // 查找替换弹窗
    searchModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-end',
    },
    searchModalContent: {
      backgroundColor: theme.backgroundRoot,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      maxHeight: '80%',
    },
    searchModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: Spacing.md,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.borderLight,
    },
    searchInputRow: {
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
    },
    searchInputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.backgroundTertiary,
      borderRadius: 10,
      paddingHorizontal: Spacing.sm,
      gap: Spacing.xs,
    },
    searchInput: {
      flex: 1,
      paddingVertical: Spacing.sm,
      fontSize: 15,
      color: theme.textPrimary,
    },
    searchResultsList: {
      maxHeight: 300,
      paddingHorizontal: Spacing.md,
    },
    searchResultSection: {
      marginBottom: Spacing.md,
    },
    synonymSectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      marginBottom: Spacing.xs,
    },
    aiTag: {
      backgroundColor: '#8B5CF6',
      paddingHorizontal: 6,
      paddingVertical: 1,
      borderRadius: 4,
    },
    searchResultItem: {
      backgroundColor: theme.backgroundTertiary,
      borderRadius: 8,
      padding: Spacing.sm,
      marginBottom: Spacing.xs,
    },
    searchResultItemActive: {
      borderWidth: 1,
      borderColor: '#C8102E',
    },
    synonymLabel: {
      marginTop: 4,
      fontStyle: 'italic',
    },
    noResultContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: Spacing.xl,
    },
    searchActions: {
      padding: Spacing.md,
      borderTopWidth: 0.5,
      borderTopColor: theme.borderLight,
    },
    searchActionBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#C8102E',
      paddingVertical: Spacing.md,
      borderRadius: 10,
    },
    searchActionBtnDisabled: {
      backgroundColor: theme.border,
    },
    // 楔子生成区域
    firstChapterGeneratingContainer: {
      backgroundColor: theme.backgroundDefault,
      marginHorizontal: Spacing.md,
      marginTop: Spacing.sm,
      borderRadius: 12,
      padding: Spacing.md,
      borderWidth: 1,
      borderColor: '#C8102E',
    },
    firstChapterHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: Spacing.sm,
      gap: Spacing.xs,
    },
    firstChapterHeaderText: {
      fontWeight: '600',
    },
    firstChapterContentBox: {
      backgroundColor: theme.backgroundTertiary,
      borderRadius: 8,
      padding: Spacing.sm,
      minHeight: 200,
      maxHeight: 400,
    },
    firstChapterContentText: {
      lineHeight: 26,
    },
    firstChapterHint: {
      marginTop: Spacing.sm,
      alignItems: 'center',
    },
    // AI模型选择与调用次数显示
    aiUsageContainer: {
      backgroundColor: theme.backgroundDefault,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.borderLight,
    },
    modelSelector: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      backgroundColor: theme.backgroundTertiary,
      marginHorizontal: Spacing.md,
      marginTop: Spacing.sm,
      borderRadius: 8,
    },
    modelSelectorLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    modelInfo: {
      gap: 1,
    },
    usageStats: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
    },
    usageProgressContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    usageProgress: {
      width: 80,
      height: 6,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: 3,
      overflow: 'hidden',
    },
    usageProgressFill: {
      height: '100%',
      backgroundColor: '#C8102E',
      borderRadius: 3,
    },
    usageRemaining: {
      backgroundColor: 'rgba(200, 16, 46, 0.1)',
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: 12,
    },
    // 模型选择下拉菜单
    modelDropdown: {
      backgroundColor: theme.backgroundDefault,
      marginHorizontal: Spacing.md,
      marginBottom: Spacing.sm,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.borderLight,
      maxHeight: 280,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    modelDropdownList: {
      maxHeight: 260,
    },
    modelOption: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      padding: Spacing.md,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.borderLight,
    },
    modelOptionActive: {
      backgroundColor: 'rgba(200, 16, 46, 0.05)',
    },
    modelOptionContent: {
      flex: 1,
      gap: 4,
    },
    modelOptionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    modelOptionFooter: {
      flexDirection: 'row',
      marginTop: 4,
    },
    modelLimitTag: {
      backgroundColor: 'rgba(200, 16, 46, 0.1)',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 10,
    },
    modelCheckIcon: {
      marginLeft: Spacing.sm,
      marginTop: 2,
    },
    // 字数提醒弹窗
    wordCountAlertOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: Spacing.lg,
    },
    wordCountAlertContent: {
      backgroundColor: theme.backgroundRoot,
      borderRadius: 16,
      padding: Spacing.xl,
      width: '100%',
      maxWidth: 340,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
    },
    wordCountAlertIcon: {
      marginBottom: Spacing.md,
    },
    wordCountAlertTitle: {
      marginBottom: Spacing.sm,
    },
    wordCountAlertText: {
      textAlign: 'center',
      marginBottom: Spacing.xs,
    },
    wordCountAlertHint: {
      textAlign: 'center',
      lineHeight: 20,
    },
    wordCountAlertButtons: {
      flexDirection: 'row',
      marginTop: Spacing.lg,
      gap: Spacing.md,
    },
    wordCountAlertButtonPrimary: {
      flex: 1,
      backgroundColor: '#C8102E',
      paddingVertical: Spacing.sm + 2,
      paddingHorizontal: Spacing.md,
      borderRadius: 8,
      alignItems: 'center',
    },
    // 配角列表样式
    sideCharacterList: {
      flexDirection: 'row',
      marginTop: Spacing.xs,
      paddingHorizontal: Spacing.sm,
    },
    sideCharacterItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.backgroundTertiary,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: BorderRadius.full,
      marginRight: Spacing.xs,
      gap: 4,
    },
    // 添加配角选择框
    addSideCharacterModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: Spacing.xl,
    },
    addSideCharacterModalContent: {
      backgroundColor: theme.backgroundDefault,
      borderRadius: 16,
      width: '100%',
      maxWidth: 400,
    },
    addSideCharacterModalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: Spacing.md,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    addSideCharacterModalBody: {
      padding: Spacing.md,
      gap: Spacing.sm,
    },
    addSideCharacterOption: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: Spacing.md,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: 12,
      gap: Spacing.md,
    },
    addSideCharacterOptionIcon: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: 'rgba(200, 16, 46, 0.1)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    addSideCharacterOptionContent: {
      flex: 1,
    },
    wordCountAlertButtonSecondary: {
      flex: 1,
      backgroundColor: 'transparent',
      borderWidth: 1,
      borderColor: '#C8102E',
      paddingVertical: Spacing.sm + 2,
      paddingHorizontal: Spacing.md,
      borderRadius: 8,
      alignItems: 'center',
    },
  });
};
